// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attempt struct {
	DeliveryID string             `json:"delivery_id"`
	Number     int32              `json:"number"`
	StatusCode int32              `json:"status_code"`
	Error      string             `json:"error"`
	DurationMs int64              `json:"duration_ms"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Delivery struct {
	ID             string             `json:"id"`
	EndpointID     string             `json:"endpoint_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseToken     pgtype.Text        `json:"lease_token"`
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Endpoint struct {
	ID        string             `json:"id"`
	Url       string             `json:"url"`
	Secret    string             `json:"secret"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
