// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claim = `-- name: Claim :one
WITH candidate AS (
 SELECT id FROM deliveries
 WHERE (status = 'pending' AND next_attempt_at <= now())
 OR (status = 'processing' AND lease_until < now())
 ORDER BY next_attempt_at, created_at
 FOR UPDATE SKIP LOCKED LIMIT 1
)
UPDATE deliveries d SET status = 'processing', lease_token = $1,
 lease_until = now() + interval '60 seconds', updated_at = now()
FROM candidate c WHERE d.id = c.id RETURNING d.id, d.endpoint_id, d.idempotency_key, d.payload, d.status, d.attempts, d.max_attempts, d.next_attempt_at, d.lease_token, d.lease_until, d.created_at, d.updated_at
`

func (q *Queries) Claim(ctx context.Context, leaseToken pgtype.Text) (Delivery, error) {
	row := q.db.QueryRow(ctx, claim, leaseToken)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (id, endpoint_id, idempotency_key, payload)
VALUES ($1,$2,$3,$4) ON CONFLICT (idempotency_key) DO NOTHING RETURNING id, endpoint_id, idempotency_key, payload, status, attempts, max_attempts, next_attempt_at, lease_token, lease_until, created_at, updated_at
`

type CreateDeliveryParams struct {
	ID             string `json:"id"`
	EndpointID     string `json:"endpoint_id"`
	IdempotencyKey string `json:"idempotency_key"`
	Payload        []byte `json:"payload"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.ID,
		arg.EndpointID,
		arg.IdempotencyKey,
		arg.Payload,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (id, url, secret) VALUES ($1,$2,$3) RETURNING id, url, secret, created_at
`

type CreateEndpointParams struct {
	ID     string `json:"id"`
	Url    string `json:"url"`
	Secret string `json:"secret"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint, arg.ID, arg.Url, arg.Secret)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const finish = `-- name: Finish :one
UPDATE deliveries SET status = $3, attempts = attempts + 1,
 next_attempt_at = $4, lease_token = NULL, lease_until = NULL, updated_at = now()
WHERE id = $1 AND lease_token = $2 AND status = 'processing'
RETURNING attempts
`

type FinishParams struct {
	ID            string             `json:"id"`
	LeaseToken    pgtype.Text        `json:"lease_token"`
	Status        string             `json:"status"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) Finish(ctx context.Context, arg FinishParams) (int32, error) {
	row := q.db.QueryRow(ctx, finish,
		arg.ID,
		arg.LeaseToken,
		arg.Status,
		arg.NextAttemptAt,
	)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const getByKey = `-- name: GetByKey :one
SELECT id, endpoint_id, idempotency_key, payload, status, attempts, max_attempts, next_attempt_at, lease_token, lease_until, created_at, updated_at FROM deliveries WHERE idempotency_key = $1
`

func (q *Queries) GetByKey(ctx context.Context, idempotencyKey string) (Delivery, error) {
	row := q.db.QueryRow(ctx, getByKey, idempotencyKey)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, endpoint_id, idempotency_key, payload, status, attempts, max_attempts, next_attempt_at, lease_token, lease_until, created_at, updated_at FROM deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id string) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, url, secret, created_at FROM endpoints WHERE id = $1
`

func (q *Queries) GetEndpoint(ctx context.Context, id string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const listAttempts = `-- name: ListAttempts :many
SELECT delivery_id, number, status_code, error, duration_ms, created_at FROM attempts WHERE delivery_id = $1 ORDER BY number
`

func (q *Queries) ListAttempts(ctx context.Context, deliveryID string) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listAttempts, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.DeliveryID,
			&i.Number,
			&i.StatusCode,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAttempt = `-- name: RecordAttempt :exec
INSERT INTO attempts (delivery_id, number, status_code, error, duration_ms)
VALUES ($1,$2,$3,$4,$5)
`

type RecordAttemptParams struct {
	DeliveryID string `json:"delivery_id"`
	Number     int32  `json:"number"`
	StatusCode int32  `json:"status_code"`
	Error      string `json:"error"`
	DurationMs int64  `json:"duration_ms"`
}

func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) error {
	_, err := q.db.Exec(ctx, recordAttempt,
		arg.DeliveryID,
		arg.Number,
		arg.StatusCode,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const replay = `-- name: Replay :one
UPDATE deliveries SET status = 'pending', max_attempts = attempts + 8,
 next_attempt_at = now(), updated_at = now()
WHERE id = $1 AND status = 'dead' RETURNING id, endpoint_id, idempotency_key, payload, status, attempts, max_attempts, next_attempt_at, lease_token, lease_until, created_at, updated_at
`

func (q *Queries) Replay(ctx context.Context, id string) (Delivery, error) {
	row := q.db.QueryRow(ctx, replay, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.IdempotencyKey,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LeaseToken,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
